project:
  title: "DBI Referat: Data Modeling"
  type: default
  output-dir: _site

format:
  revealjs:
    theme: simple
    slide-level: 2
    controls: true
    progress: true
    history: true
    center: true
    transition: slide
    background-transition: fade
    slide-number: c/t
    show-slide-number: all
    pdf-separate-fragments: false
  pdf:
    output-file: referat
    documentclass: scrartcl
    papersize: a4
    toc: true
    number-sections: true

filters:
  - diagram

author: "Dein Name"
date: "2026-09-29"
lang: de
